tap "buildpacks/tap"
tap "steipete/tap"
brew "cryptography"
brew "tree"
brew "ansible"
brew "ansible-lint"
brew "argo"
brew "argocd"
brew "arping"
brew "asciinema"
brew "awscli"
brew "black"
brew "chezmoi"
brew "cocoapods"
brew "coreutils"
brew "cri-tools"
brew "dive"
brew "docutils"
brew "eza"
brew "fx"
brew "fzf"
brew "gh"
brew "glow"
brew "go"
brew "grpcurl"
brew "helm"
brew "hugo"
brew "webp"
brew "jq"
brew "kubernetes-cli"
brew "krew"
brew "kubecm"
brew "kustomize"
brew "libwebsockets"
brew "llvm"
brew "lolcat"
brew "lsusb"
brew "lua"
brew "luarocks"
brew "mackup"
brew "mas"
brew "micropython"
brew "minio-mc"
brew "mosquitto"
brew "neofetch"
brew "neovim"
brew "net-snmp"
brew "node"
brew "netlify-cli"
brew "nyancat"
brew "openclaw-cli"
brew "opentofu"
brew "pipx"
brew "protobuf"
brew "python@3.10"
brew "python@3.11"
brew "python@3.12"
brew "rust"
brew "starship"
brew "stern"
brew "terminal-notifier"
brew "watch"
brew "wget"
brew "whosthere"
brew "yamllint"
brew "buildpacks/tap/pack"
brew "steipete/tap/imsg"
cask "1password-cli"
cask "claude-code"
cask "rar"
cask "warp"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Hidden Bar", id: 1452453066
mas "Home Assistant", id: 1099568401
mas "Labelife", id: 1560922539
mas "Magnet", id: 441258766
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 375589283
mas "Slack", id: 803453959
mas "Speedtest", id: 1153157709
mas "Trello", id: 1278508951
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
mas "Yubico Authenticator", id: 1497506650
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "anthropic.claude-code"
vscode "docker.docker"
vscode "github.codespaces"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "marlinfirmware.auto-build"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.live-server"
vscode "ms-vscode.remote-explorer"
vscode "redhat.ansible"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "sumneko.lua"
vscode "tamasfe.even-better-toml"
vscode "vue.volar"
vscode "zxh404.vscode-proto3"
go "github.com/go-delve/delve/cmd/dlv"
go "github.com/ramya-rao-a/go-outline"
go "golang.org/x/tools/cmd/godoc"
go "github.com/fatih/gomodifytags"
go "github.com/haya14busa/goplay/cmd/goplay"
go "golang.org/x/tools/gopls"
go "github.com/cweill/gotests/gotests"
go "github.com/fullstorydev/grpcui/cmd/grpcui"
go "github.com/josharian/impl"
go "google.golang.org/protobuf/cmd/protoc-gen-go"
go "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
go "honnef.co/go/tools/cmd/staticcheck"
krew "cert-manager"
krew "ctx"
krew "get-all"
krew "node-shell"
krew "ns"
krew "oidc-login"
krew "resource-capacity"
